cask_args appdir: '/Applications'

brew 'autoconf'
brew 'automake'
brew 'asdf'
brew 'coreutils'
brew 'gpg'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libtool'
brew 'libxslt'
brew 'libyaml'
brew 'neovim'
brew 'openssl'
brew 'postgresql'
brew 'python3'
brew 'readline'
brew 'ripgrep'
brew 'roundup'
brew 'spaceman-diff'
brew 'the_silver_searcher'
brew 'unixodbc'
brew 'unrar'
brew 'wget'
brew 'yarn', args: ['without-node']
brew 'youtube-dl'

cask 'adium'
cask 'google-chrome'
cask 'handbrake'
cask 'java'
cask 'ngrok'
cask 'slack'
cask 'soundflower'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'zoomus'
